env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - plugin:react-hooks/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  react/react-in-jsx-scope: "off"
  react/no-array-index-key:
    - error
  array-callback-return:
    - error
    - allowImplicit: true
  react/jsx-no-duplicate-props:
    - error
    - ignoreCase: true
  react/jsx-no-undef:
    - error
  react/jsx-pascal-case:
    - error
    - allowAllCaps: true
  react/no-danger:
    - warn
  react/jsx-tag-spacing:
    - error
    - closingSlash: never
      beforeSelfClosing: always
      afterOpening: never
      beforeClosing: never
  react/no-unused-state:
    - error
  react/button-has-type:
    - error
    - button: true
      submit: true
      reset: false
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - error
